//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Osekai.Octon.Database.EntityFramework.MySql {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MySqlDataPopulatorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MySqlDataPopulatorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Osekai.Octon.Database.EntityFramework.MySql.MySqlDataPopulatorResources", typeof(MySqlDataPopulatorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `BeatmapPacksForMedals` VALUES (10,0,1),(10,0,2),(10,0,3),(54,0,0),(154,0,0),(155,0,0),(156,0,0),(170,0,0),(171,0,0),(187,0,3),(221,0,0),(222,0,0),(235,0,0),(235,0,1),(235,0,3),(269,0,0),(272,0,0),(273,0,0),(275,0,0),(276,0,0),(277,0,0),(278,0,0),(279,0,0),(280,0,0),(281,0,0),(7,40,0),(8,41,0),(9,42,0),(10,43,0),(11,48,0),(12,49,0),(14,70,0),(18,93,0),(19,94,0),(25,207,0),(26,208,0),(27,209,0),(34,363,0),(37,364,0),(35,365,0),(36,366,0),(162,1186,0),(162,1187,1),(162,1188,2),(162,1189,3),(163,12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sql {
            get {
                return ResourceManager.GetString("Sql", resourceCulture);
            }
        }
    }
}
