// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Osekai.Octon.Persistence.EntityFramework.MySql;

#nullable disable

namespace Osekai.Octon.Persistence.EntityFramework.MySql.Migrations
{
    [DbContext(typeof(MySqlOsekaiDbContext))]
    [Migration("20230103131639_FixMedalRaritiesAndAddMedalSettings")]
    partial class FixMedalRaritiesAndAddMedalSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_general_ci")
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Experimental")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("SimpleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SimpleName"), "ascii");

                    b.Property<bool>("Visible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Apps", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.AppTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Color"), "ascii");

                    b.Property<string>("DarkColor")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("DarkColor"), "ascii");

                    b.Property<float>("DarkHslValueMultiplier")
                        .HasColumnType("float");

                    b.Property<bool>("HasCover")
                        .HasColumnType("tinyint(1)");

                    b.Property<float>("HslValueMultiplier")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("AppId")
                        .IsUnique();

                    b.HasIndex(new[] { "AppId" }, "fk_AppId_idx");

                    b.ToTable("AppThemes", (string)null);
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.BeatmapPack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BeatmapCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BeatmapPacks");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.BeatmapPackForMedal", b =>
                {
                    b.Property<int>("MedalId")
                        .HasColumnType("int");

                    b.Property<int>("BeatmapPackId")
                        .HasColumnType("int");

                    b.Property<int>("Gamemode")
                        .HasColumnType("int");

                    b.HasKey("MedalId", "BeatmapPackId", "Gamemode");

                    b.HasIndex("BeatmapPackId");

                    b.ToTable("BeatmapPacksForMedals");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.CacheEntry", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Name"), "ascii");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("blob");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Name");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CacheEntries", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.HomeFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalizationPrefix")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("varchar(40)")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("LocalizationPrefix"), "ascii");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("tinytext");

                    b.HasKey("Id");

                    b.ToTable("HomeFaqs", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Medal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstAchievedBy")
                        .HasColumnType("tinytext");

                    b.Property<DateTimeOffset?>("FirstAchievedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Grouping")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<int>("Ordering")
                        .HasColumnType("int");

                    b.Property<string>("Restriction")
                        .HasMaxLength(8)
                        .HasColumnType("varchar");

                    b.Property<string>("Video")
                        .HasColumnType("tinytext");

                    b.HasKey("Id");

                    b.ToTable("Medals", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalRarity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<float>("Frequency")
                        .HasColumnType("float");

                    b.Property<int>("MedalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedalId")
                        .IsUnique();

                    b.ToTable("MedalRarities");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Locked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MedalId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedalId")
                        .IsUnique();

                    b.ToTable("MedalSettings");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalSolution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MedalId")
                        .HasColumnType("int");

                    b.Property<int>("Mods")
                        .HasColumnType("int");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("SubmittedBy"), "ascii");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MedalId")
                        .IsUnique();

                    b.ToTable("MedalSolutions");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Session", b =>
                {
                    b.Property<string>("Token")
                        .HasMaxLength(32)
                        .HasColumnType("char")
                        .UseCollation("ascii_general_ci");

                    MySqlPropertyBuilderExtensions.HasCharSet(b.Property<string>("Token"), "ascii");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Token");

                    b.ToTable("Sessions", (string)null);

                    MySqlEntityTypeBuilderExtensions.UseCollation(b, "utf8mb4_general_ci");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.AppTheme", b =>
                {
                    b.HasOne("Osekai.Octon.Persistence.EntityFramework.MySql.Models.App", "App")
                        .WithOne("AppTheme")
                        .HasForeignKey("Osekai.Octon.Persistence.EntityFramework.MySql.Models.AppTheme", "AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_AppId");

                    b.Navigation("App");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.BeatmapPackForMedal", b =>
                {
                    b.HasOne("Osekai.Octon.Persistence.EntityFramework.MySql.Models.BeatmapPack", "BeatmapPack")
                        .WithMany("MedalsForBeatmapPack")
                        .HasForeignKey("BeatmapPackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Medal", "Medal")
                        .WithMany("BeatmapPacksForMedal")
                        .HasForeignKey("MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeatmapPack");

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalRarity", b =>
                {
                    b.HasOne("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Medal", "Medal")
                        .WithOne("Rarity")
                        .HasForeignKey("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalRarity", "MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalSettings", b =>
                {
                    b.HasOne("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Medal", "Medal")
                        .WithOne("Settings")
                        .HasForeignKey("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalSettings", "MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalSolution", b =>
                {
                    b.HasOne("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Medal", "Medal")
                        .WithOne("Solution")
                        .HasForeignKey("Osekai.Octon.Persistence.EntityFramework.MySql.Models.MedalSolution", "MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medal");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.App", b =>
                {
                    b.Navigation("AppTheme");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.BeatmapPack", b =>
                {
                    b.Navigation("MedalsForBeatmapPack");
                });

            modelBuilder.Entity("Osekai.Octon.Persistence.EntityFramework.MySql.Models.Medal", b =>
                {
                    b.Navigation("BeatmapPacksForMedal");

                    b.Navigation("Rarity");

                    b.Navigation("Settings");

                    b.Navigation("Solution");
                });
#pragma warning restore 612, 618
        }
    }
}
